### ISSUE TITLE
How to retrieve game logs?

### ISSUE THREAD

**Issue by joshk0** [MahjongRepository/mahjong_soul_api#1]
I see that you have built many utilities, and there are many more out there, for interacting with Tenhou game logs.

In contrast, there are very few to none for processing Majsoul game logs. There is one that claims to turn your 'share' link from the game:

https://mahjongsoul.game.yo-star.com/?paipu=201129-19398ca4-e825-40d6-9ee5-a5f8175dcb50_a924963243

Into one that can be used to download a protobuf payload, generating a URL like this: 

https://mjusgs.mahjongsoul.com:2882/majsoul/game_record/201129-19398ca4-e825-40d6-9ee5-a5f8175dcb50_a924963243

But that URL doesn't connect at all anymore, so I'm guessing this service is not working anymore.

Since its clear you think a lot about processing game logs to get insights, I am curious if you have already tried to retrieve majsoul game logs using the Websockets API. Since the data is made available to the clients, it surely must be in there. But I searched for 'paipu' and 'log' in the list of rpc methods and didn't find anything. Could you help point me in the right direction?

Related issue: https://github.com/Euophrys/Riichi-Trainer/issues/49

**Comment by Nihisil** [comment]
I didn't try to do it myself, but looking on MS requests you need to use `fetch_game_record_list()` to get a list of logs (you can find usage of this method here: https://github.com/MahjongRepository/mahjong_soul_api/blob/master/example.py#L99

Or you can get log IDs from other place.

And after that, you need to use the `fetch_game_record()` method in the same WS session to get game log content by ID. It will return protobuf with protobuf that you need to parse recursively.

Let me know if that helps.

**Comment by Nihisil** [comment]
There is example how to use this function: https://github.com/MahjongRepository/mahjong_soul_api/pull/2/commits/03ffda6045177ae6972872eac521f2e178942985
