### ISSUE TITLE
How do we "prepare" the latest `liqi_admin.json`?

### ISSUE THREAD

**Issue by peter1357908** [MahjongRepository/mahjong_soul_api#14]
Hello, I want to update the protocol files for the contest manager API (just for future reference), but I got stuck at the very first step:
> Prepare new `liqi_admin.json` file from MS tournament manager panel

I already know how to download `liqi.json`, but I couldn't find documentation for downloading/generating `liqi_admin.json`.

Thank you!

**Comment by peter1357908** [comment]
By the way, I wrote scripts for updating the protocol files for an installed `ms_api` package, given `liqi.json` and `liqi_admin.json`. I want to know how to download/generate `liqi_admin.json` so I can fully automate the process.

**Comment by Nihisil** [comment]
I didn't add the admin API, but you can try finding the `liqi_admin.json` file somewhere here: https://mahjongsoul.tournament.yo-star.com/dhs/index.html#/login. 

You might need to create a tournament first to be able to see these protobuffs (it costs around 60 currency).

The original author of the admin files might have more information @unStatiK

**Comment by peter1357908** [comment]
Yeah, I tried digging around in the tournament management websites (both CN and EN), but couldn't find it. I posted [an issue under another repo in Chinese](https://github.com/takayama-lily/mjsoul/issues/10) asking basically about the same thing (curiously it's named differently -- `dhs.json`). I'll post any update I get here.

(btw I already have a few tournaments set up and am currently trying to write a bot to automate score exportation, etc.)

**Comment by unStatiK** [comment]
@peter1357908 Hello, thanks for interest our software!

For grabbing liqi_admin.json you should manually complete next steps:

1. Go to https://mahjongsoul.tournament.yo-star.com/dhs/index.html#/login and then in web console search app.js
![1](https://github.com/MahjongRepository/mahjong_soul_api/assets/343531/487841f4-9771-4815-9c79-e2e28b45086e)

2. Then pretty print the response and search lq object :
![2](https://github.com/MahjongRepository/mahjong_soul_api/assets/343531/0175b2be-fe07-452a-b241-6a767bd565ea)

3. Copy only e.exports value (this is JS pure object) and stringify it:
![3](https://github.com/MahjongRepository/mahjong_soul_api/assets/343531/9095c825-820c-48c4-a846-28b7762bb110)

4. Success! You get liqi_admin.json, strongly recommend check this json with linters :
![4](https://github.com/MahjongRepository/mahjong_soul_api/assets/343531/cffcb2f7-fb04-462b-9e78-2e5382a560d1)

**Comment by peter1357908** [comment]
Thank you! I actually peeked at that obfuscated `app.xxx.js` before and found that particular object interesting, but completely forgot about it later!

I appreciate the detailed guide.
