### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by icnsnker** [MahjongRepository/mahjong_soul_api#21]
async def load_GameRecord_List(manager_api):
    logging.info("Loading GameRecord list...")

    req = pb.ReqFetchCustomizedContestGameRecordList()
    #req.last_index = 1
    res = await manager_api.fetch_contest_game_records(req)
    logging.info(res)
    return True

In fetchContestGameRecords req is ReqFetchCustomizedContestGameRecordList

ReqFetchCustomizedContestGameRecordList   ：  last_index   int

No matter what value is assigned to last_index or None, error code=2501 will always be returned.

I'm really confused. Could you please give me some guidance?

**Comment by icnsnker** [comment]
token has been obtained

**Comment by icnsnker** [comment]
https://mahjongsoul.tournament.yo-star.com/dhs/index.html#/login：
(function () {
  window.__MJ_DHS_URL__ = 'https://mahjongsoul.tournament.yo-star.com/dhs/index.html';
  window.__MJ_DHS_REDIRECT__ = 'https://mahjongsoul.tournament.yo-star.com/dhs/redirect';
  window.__MJ_DHS_LB__ = 'https://mjusgs.mahjongsoul.com:7988';
  window['__MJ_GAME_INFO_API__'] = 'http://mjusgs.mahjongsoul.com:7443';
  window['__MJ_DHS_WS__']="wss://mjusgs.mahjongsoul.com:9443"
})()

https://www.maj-soul.com/dhs/#/login：
(function () {
  window['__MJ_DHS_LB__'] = 'https://common-v2.maj-soul.com';
  window['__MJ_GAME_INFO_API__'] = 'https://common-v2.maj-soul.com';
  window['__MJ_DHS_WS__']="wss://common-v2.maj-soul.com/contest_ws_gateway"
})()

The configuration is different

**Comment by unStatiK** [comment]
@icnsnker , Hello, thanks for interest our software!

To get contest's records firstly you should enter it. 
```
req = pb.ReqManageContest()
req.unique_id = <your_contest_unique_id>  // at the end of the URL of the tournament management panel
res = await manager_api.manage_contest(req)
```

Then  you can success load contest's records without error code 2501
```
req = pb.ReqFetchCustomizedContestGameRecordList()
res = await manager_api.fetch_contest_game_records(req)
```
