### ISSUE TITLE
Empty Array in `game_details.records`

### ISSUE THREAD

**Issue by Jim137** [MahjongRepository/mahjong_soul_api#22]
Hello,

I've encountered an issue while trying to retrieve the game log for a Sanma game using the mahjong_soul_api. I followed the example provided in the repository ([example.py lines 140-170](https://github.com/MahjongRepository/mahjong_soul_api/blob/master/example.py#L140:L170)). However, I noticed that the game_details.records array is returning empty for the Sanma game I attempted to log.

Could you please help me understand if I'm missing a step in the process, or is the API's current functionality limited to Yonma games only? Any guidance or suggestions on how to correctly retrieve Sanma game logs would be greatly appreciated.

Thank you for your assistance.

**Comment by unStatiK** [comment]
@Jim137 You should use game_details.actions  istead game_details.records. Example outdated and isn't relevant for current protobuf protocol definition.

**Comment by Jim137** [comment]
Thank you! I will look up the new protocol definition.
